Repository Ayush7614/Bundli-Frontend, pull requests merged in 2021-07, with the labels that each got.

#121 Rock-Paper-Scissors game
  README.md
  Rock-Paper-Scissors game/Images/Ouput.gif
  Rock-Paper-Scissors game/Images/Output20.png
  Rock-Paper-Scissors game/Images/Output21.png
  Rock-Paper-Scissors game/Images/Output22.png
  Rock-Paper-Scissors game/Images/Output23.png
  Rock-Paper-Scissors game/Images/Output24.png
  Rock-Paper-Scissors game/Images/text
  Rock-Paper-Scissors game/index.html
  Rock-Paper-Scissors game/readme.md
  Rock-Paper-Scissors game/script/script.js
  Rock-Paper-Scissors game/style/style.css
Labels: HCSSoC21, accepted

#138 Added payment integration
  Payment-integration/detail.css
  Payment-integration/details.html
  Payment-integration/index.html
  Payment-integration/payment.js
  Payment-integration/style.css
  README.md
  Screenshots/Payment-integration.png
Labels: HCSSoC21, accepted

#174 Added Image to text CSS converter in JS
  README.md
  Screenshots/image-converter.PNG
  image-converter/click.mp3
  image-converter/image-converter.PNG
  image-converter/index.html
  image-converter/index.js
  image-converter/logo.png
  image-converter/styles.css
  image-converter/win.wav
Labels: HCSSoC21, accepted

#171 Split_screen_effect
  README.md
  Split_screen_effect/README.md
  Split_screen_effect/css/style.css
  Split_screen_effect/img/1.jpg
  Split_screen_effect/img/2.jpg
  Split_screen_effect/index.html
  Split_screen_effect/js/main.js
  Split_screen_effect/screen-split.gif
Labels: HCSSoC21, accepted

#191 Added Loading Animation
  .github/.DS_Store
  Brick Breakout Game/.DS_Store
  Carousel/.DS_Store
  Color Flipper/.DS_Store
  Connect Four/.DS_Store
  Drum-Kit/.DS_Store
  Feature Card Component/.DS_Store
  Find the word/.DS_Store
  Hangman/.DS_Store
  Loading Animation/index.html
  Loading Animation/styles.css
  Memory Game/.DS_Store
  Minesweeper Game/.DS_Store
  Music-player/.DS_Store
  Pricing Card/.DS_Store
  Profile Card View/.DS_Store
  Project-Website/.DS_Store
  README.md
  Rock-Paper-Scissors game/.DS_Store
  Screenshots/Loading Animation.gif
  Simple Chatroom/.DS_Store
  Social Media Dashboard/.DS_Store
  Tic-Tac-Toe/.DS_Store
  Vaccine Slot Finder/.DS_Store
  Whack a mole game/.DS_Store
  admin dashboard/.DS_Store
  flappybird/.DS_Store
Labels: HCSSoC21, accepted

#192 Added Calculator with improved UI and features
  Calculator/css/styles.css
  Calculator/index.html
  Calculator/js/.DS_Store
  Calculator/js/index.js
  README.md
  Screenshots/Calculator Dark Mode.png
  Screenshots/Calculator Light Mode.png
Labels: HCSSoC21, accepted

#195 Added expand button animation
  Expand-button-animation/index.html
  Expand-button-animation/script.js
  Expand-button-animation/style.css
  README.md
  Screenshots/Expand_button.gif
Labels: HCSSoC21, accepted

#201 Added typewriter Animation
  README.md
  Screenshots/typewriter.gif
  Typewriter-effect/index.html
  Typewriter-effect/style.css
Labels: HCSSoC21, accepted

#206 wall breaker
  README.md
  Screenshots/wallbreaker.png
  Wall Breaker/README.md
  Wall Breaker/index.css
  Wall Breaker/index.html
  Wall Breaker/index.js
  Wall Breaker/music/gameover.mp3
  Wall Breaker/music/move.mp3
Labels: DCP`21, accepted

#209 Added Card Hover Effect
  Card Hover Effect/index.html
  Card Hover Effect/styles.css
  README.md
  Screenshots/.DS_Store
  Screenshots/card-hover-effect.gif
Labels: HCSSoC21, accepted

#214 Added Background Changer
  README.md
  Screenshots/background-changer.gif
  background-color-changer/index.html
  background-color-changer/script.js
  background-color-changer/style.css
Labels: HCSSoC21, accepted

#207 Added Rainbow Strip Buttons
  README.md
  Rainbow Strip Button/index.html
  Rainbow Strip Button/styles.css
  Screenshots/rainbow-button.gif
Labels: HCSSoC21, accepted

#220 Snake Game
  Snake Game/Images/Output.gif
  Snake Game/Images/Output4.png
  Snake Game/Images/Output5.png
  Snake Game/Images/Output6.png
  Snake Game/Images/text
  Snake Game/Snake-Game.png
  Snake Game/images/apple1.png
  Snake Game/images/mango.png
  Snake Game/images/pear.png
  Snake Game/images/wp2409705.jpg
  Snake Game/index.html
  Snake Game/readme.md
  Snake Game/script.js
  Snake Game/snake.js
  Snake Game/style.css
Labels: DCP`21, accepted

#233 CodeOfConduct added
  CODE_OF_CONDUCT.md
Labels: DCP`21, accepted

#234 Added bubble navbar animation
  Navbar-Bubble-Animation/index.html
  Navbar-Bubble-Animation/script.js
  Navbar-Bubble-Animation/style.css
  README.md
  Screenshots/Bubble-Navbar.gif
Labels: HCSSoC21, accepted

#236 Cloud Animation
  Cloud_Animation/README.md
  Cloud_Animation/index.html
  Cloud_Animation/one.css
Labels: DCP`21, accepted

#248 Liquid Loader Animation
  Liquid_Loader_Animation/image/image1.png
  Liquid_Loader_Animation/image/image2.png
  Liquid_Loader_Animation/index.html
  Liquid_Loader_Animation/style.css
Labels: DCP`21, accepted

#243 Neuromorphic Calculator added
  Neuromorphic Calculator/calculator.png
  Neuromorphic Calculator/index.html
  Neuromorphic Calculator/style.css
  README.md
Labels: DCP`21, accepted

#262 Added Glassmorphic Short Resume
  Glassmorphic Short Resume/index.html
  Glassmorphic Short Resume/styles.css
  README.md
  Screenshots/Glassmorphic Short Resume.png
Labels: HCSSoC21, accepted

#273 Bubble shooter
  Bubble Shooter Game/bubbleshooter.html
  README.md
  Screenshots/Bubble Shooter Game.JPG
Labels: PSoC21, accepted

#260 created front-end for illustrator
  Illustrator/images/p1.jfif
  Illustrator/images/p2.jpg
  Illustrator/images/p3.webp
  Illustrator/images/p4.png
  Illustrator/images/p5.png
  Illustrator/images/p6.jpg
  Illustrator/images/p7.jpg
  Illustrator/images/p8.jpg
  Illustrator/images/p9.jpg
  Illustrator/images/sample.png
  Illustrator/index.html
  Illustrator/readme.md
  README.md
Labels: DCP`21, Level1, accepted

#268 Modify code for better user experience
  Chat App/README.md
  Chat App/chatLeftPage.png
  Chat App/chatPage.png
  Chat App/landingPage.png
  Chat App/package-lock.json
  Chat App/package.json
  Chat App/public/chat.html
  Chat App/public/css/style.css
  Chat App/public/index.html
  Chat App/server.js
  Chat App/utils/messages.js
Labels: DCP`21, accepted

#280 Added Angular Bootstrap Route
  README.md
  Screenshots/Angular-Route.PNG
  angular-route/angular-route/.browserslistrc
  angular-route/angular-route/.editorconfig
  angular-route/angular-route/.gitignore
  angular-route/angular-route/README.md
  angular-route/angular-route/angular.json
  angular-route/angular-route/karma.conf.js
  angular-route/angular-route/package-lock.json
  angular-route/angular-route/package.json
  angular-route/angular-route/src/app/app-routing.module.ts
  angular-route/angular-route/src/app/app.component.css
  angular-route/angular-route/src/app/app.component.html
  angular-route/angular-route/src/app/app.component.spec.ts
  angular-route/angular-route/src/app/app.component.ts
  angular-route/angular-route/src/app/app.module.ts
  angular-route/angular-route/src/app/container1/container1.component.css
  angular-route/angular-route/src/app/container1/container1.component.html
  angular-route/angular-route/src/app/container1/container1.component.spec.ts
  angular-route/angular-route/src/app/container1/container1.component.ts
  angular-route/angular-route/src/app/container2/container2.component.css
  angular-route/angular-route/src/app/container2/container2.component.html
  angular-route/angular-route/src/app/container2/container2.component.spec.ts
  angular-route/angular-route/src/app/container2/container2.component.ts
  angular-route/angular-route/src/app/container3/container3.component.css
  angular-route/angular-route/src/app/container3/container3.component.html
  angular-route/angular-route/src/app/container3/container3.component.spec.ts
  angular-route/angular-route/src/app/container3/container3.component.ts
  angular-route/angular-route/src/app/container4/container4.component.css
  angular-route/angular-route/src/app/container4/container4.component.html
  angular-route/angular-route/src/app/container4/container4.component.spec.ts
  angular-route/angular-route/src/app/container4/container4.component.ts
  angular-route/angular-route/src/app/navbar/navbar.component.css
  angular-route/angular-route/src/app/navbar/navbar.component.html
  angular-route/angular-route/src/app/navbar/navbar.component.spec.ts
  angular-route/angular-route/src/app/navbar/navbar.component.ts
  angular-route/angular-route/src/assets/.gitkeep
  angular-route/angular-route/src/assets/Angular Route.PNG
  angular-route/angular-route/src/environments/environment.prod.ts
  angular-route/angular-route/src/environments/environment.ts
  angular-route/angular-route/src/favicon.ico
  angular-route/angular-route/src/index.html
  angular-route/angular-route/src/main.ts
  angular-route/angular-route/src/polyfills.ts
  angular-route/angular-route/src/styles.css
  angular-route/angular-route/src/test.ts
  angular-route/angular-route/tsconfig.app.json
  angular-route/angular-route/tsconfig.json
  angular-route/angular-route/tsconfig.spec.json
Labels: DCP`21, Level2

#281 Water Drop Effect added
  README.md
  Water Drop Effect/image.png
  Water Drop Effect/index.html
  Water Drop Effect/style.css
Labels: DCP`21, Level1
