Repository Ayush7614/Bundli-Frontend, pull requests merged in 2021-10, with the labels that each got.

#320 Scroll Animation Project
  Scroll animation/index.html
  Scroll animation/script.js
  Scroll animation/style.css
Labels: open-source, accepted, hacktoberfest2021, hacktoberfest-accepted

#329 Added Animated Service cards
  README.md
  Screenshots/service-cards.PNG
  service-card/app.png
  service-card/index.html
  service-card/service-cards.PNG
  service-card/style.css
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#350 Added CSS grid demo as per CSS Grid demo #345
  GridDemo/index.css
  GridDemo/index.html
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#349 google_reCaptcha_integrated
  googleRecaptchaIntegration/.env
  googleRecaptchaIntegration/.gitignore
  googleRecaptchaIntegration/README.md
  googleRecaptchaIntegration/client/.gitignore
  googleRecaptchaIntegration/client/package-lock.json
  googleRecaptchaIntegration/client/package.json
  googleRecaptchaIntegration/client/public/favicon.ico
  googleRecaptchaIntegration/client/public/index.html
  googleRecaptchaIntegration/client/public/manifest.json
  googleRecaptchaIntegration/client/public/robots.txt
  googleRecaptchaIntegration/client/src/App.css
  googleRecaptchaIntegration/client/src/App.js
  googleRecaptchaIntegration/client/src/index.css
  googleRecaptchaIntegration/client/src/index.js
  googleRecaptchaIntegration/package-lock.json
  googleRecaptchaIntegration/package.json
  googleRecaptchaIntegration/server.js
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#337 Mobile TAB NAVIGATION
  mobile tab navigation/index.html
  mobile tab navigation/script.js
  mobile tab navigation/style.css
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#335 SOUND DRUM
  sound board/index.html
  sound board/script.js
  sound board/sounds/applause.mp3
  sound board/sounds/boo.mp3
  sound board/sounds/gasp.mp3
  sound board/sounds/tada.mp3
  sound board/sounds/victory.mp3
  sound board/sounds/wrong.mp3
  sound board/style.css
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#331 feat: Add BlurBoom project
  Blur_Boom_HTML_CSS/index.html
  Blur_Boom_HTML_CSS/script.js
  Blur_Boom_HTML_CSS/style.css
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#327 NEW YEAR COUNTDOWN GAME
  New year countdown/index.html
  New year countdown/script.js
  New year countdown/style.css
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#354 added as per isue Temperature Converter #347
  CovidData/app.js
  CovidData/asset/covid.png
  CovidData/asset/patient-examination-medicine-coronavirus-healthcare-concept_140689-923-removebg-preview.png
  CovidData/index.html
  CovidData/style.css
  Temperature Converter/thermometer_temperature_medical_icon_131300.ico
  Temperature Converter/viva.css
  Temperature Converter/viva.html
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#357 Added Upside Left Animated Navbar
  README.md
  Screenshots/upside-navbar.PNG
  upside-navbar/index.html
  upside-navbar/index.js
  upside-navbar/rnd.png
  upside-navbar/style.css
  upside-navbar/upside-navbar.PNG
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#359 Added as per issue Covid data getter #346
  CovidData/index.html
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#365 FontAwesome Icon
  FontAwesome icon Background Animation Effects/index.html
  FontAwesome icon Background Animation Effects/style.css
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#375 Microsoft Landing Page
  Microsoft Landing Page/index.html
  Microsoft Landing Page/phone.css
  Microsoft Landing Page/style.css
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#377 Faq Collapse
  Faq Collapse/index.html
  Faq Collapse/script.js
  Faq Collapse/style.css
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#378 Added a new icon effect from css as per which fixes #373
  icons effects/index.css
  icons effects/index.html
  icons effects/light.css
  icons effects/light.html
  icons effects/pro.png
  icons effects/readme.md
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#379 Added a new project LampAnimation
  VueLamp/Readme.md
  VueLamp/images/lamp.png
  VueLamp/images/light.png
  VueLamp/images/logo.png
  VueLamp/images/menu.png
  VueLamp/index.html
  VueLamp/index.js
  VueLamp/lamp.css
  VueLamp/pro.png
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#380 Rocket travelling
  Rocket-travelling/Readme.md
  Rocket-travelling/Script.js
  Rocket-travelling/Style.css
  Rocket-travelling/index.html
  Rocket-travelling/pro.png
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#381 Loading balls
  LoadingBalls/Readme.md
  LoadingBalls/index.html
  LoadingBalls/pro.png
  LoadingBalls/syle.css
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#392 Update style.css
  Birthday Countdown/style.css
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#393 Update main.css
  Budget_App/css/main.css
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#394 Update index.html
  Analog Watch/index.html
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#397 Update index.js
  Atomic symbol generator /index.js
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#384 Testimonial
  Testimonial/Script.js
  Testimonial/Style.css
  Testimonial/index.html
  Testimonial/pro.png
  Testimonial/readme.md
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#388 Added a new animated project fixes #369
  Automatic Image Slider Animation/image_slider.png
  Automatic Image Slider Animation/index.css
  Automatic Image Slider Animation/index.html
  Automatic Image Slider Animation/readme.md
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#391 Sort Courses on the basis of price added
  Sort Courses/README.md
  Sort Courses/index.html
  Sort Courses/sort.css
  Sort Courses/sort.gif
  Sort Courses/sort.js
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#387 Added image hover effect
  Image-Hover-Effect/images/1.png
  Image-Hover-Effect/images/2.png
  Image-Hover-Effect/images/3.png
  Image-Hover-Effect/index.html
  Image-Hover-Effect/style.css
  README.md
  Screenshots/Image_hover.mp4
  Screenshots/Img_hover.jpg
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#386 Added as per issue #Customer review webapp #348
  Dikshit customer review webapp/__pycache__/app.cpython-39.pyc
  Dikshit customer review webapp/app.py
  Dikshit customer review webapp/database/reviews.csv
  Dikshit customer review webapp/sample.html
  Dikshit customer review webapp/static/bg.jpg
  Dikshit customer review webapp/static/bg2.jpg
  Dikshit customer review webapp/static/style.css
  Dikshit customer review webapp/templates/index.html
  Dikshit customer review webapp/templates/index.jinja2
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#400 Added minions translator
  Minions translate/README.md
  Minions translate/img/banana.gif
  Minions translate/img/minion.png
  Minions translate/index.html
  Minions translate/script.js
  Minions translate/style.css
  Screenshots/minions-talk.PNG
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#407 I have updated the todo app. No. 361
  Todo App/background-design.png
  Todo App/index.html
  Todo App/style.css
Labels: open-source, accepted, hacktoberfest2021, hacktoberfest-accepted

#405 Added Responsive Animated Social Media footer
  README.md
  Screenshots/social-footer.PNG
  social-footer/index.html
  social-footer/index.js
  social-footer/social-footer.PNG
  social-footer/social-media-icons.webp
  social-footer/style.css
Labels: accepted, hacktoberfest2021, hacktoberfest-accepted

#403 feat: 🚀Add Vertical Image Slider project fixes #389
  Atomic symbol generator /README.md
  Atomic symbol generator /index.html
  Atomic symbol generator /index.js
  Atomic symbol generator /ss1.png
  Atomic symbol generator /ss2.png
  Atomic symbol generator /style.css
  Vertical_Image_Slider/index.html
  Vertical_Image_Slider/script.js
  Vertical_Image_Slider/style.css
Labels: accepted, hacktoberfest2021, hacktoberfest-accepted

#410 Added Forbidden-21 game
  Forbidden-21 Game/.vscode/settings.json
  Forbidden-21 Game/README.md
  Forbidden-21 Game/css/difficultyStyles.css
  Forbidden-21 Game/css/gamePageStyles.css
  Forbidden-21 Game/css/rulesStyles.css
  Forbidden-21 Game/forbidden21Game.png
  Forbidden-21 Game/html/gamePage.html
  Forbidden-21 Game/html/getDifficulty.html
  Forbidden-21 Game/html/index.html
  Forbidden-21 Game/img/github_icon.png
  Forbidden-21 Game/js/designMovement.js
  Forbidden-21 Game/js/gameLogic.js
  Forbidden-21 Game/js/setDifficulty.js
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#409 added screenshot of frontend developer portfolio
  README.md
Labels: open-source, hacktoberfest2021, hacktoberfest-accepted

#416 Improved UI for Github Profiles project
  Github Profiles/arrow.png
  Github Profiles/github.png
  Github Profiles/index.html
  Github Profiles/script.js
  Github Profiles/style.css
Labels: accepted, hacktoberfest2021, hacktoberfest-accepted

#412 added "Morse Code Project"
  Morse code/img/output-onlinegiftools.gif
  Morse code/index.html
  Morse code/script.js
  Morse code/style.css
Labels: open-source, accepted, hacktoberfest2021, hacktoberfest-accepted

#404 Added Dynamic JS keyboard
  JS-Keyboard/index.html
  JS-Keyboard/index.js
  JS-Keyboard/js-keyboard.PNG
  JS-Keyboard/keyboard.jpg
  JS-Keyboard/style.css
  README.md
  Screenshots/js-keyboard.PNG
Labels: accepted, hacktoberfest2021, hacktoberfest-accepted

#427 Update style.css
  Birthday Countdown/style.css
Labels: accepted, hacktoberfest2021, hacktoberfest-accepted
