Repository Ayush7614/Bundli-Frontend, pull requests merged in 2022-05, with the labels that each got.

#689 Plantix-Diagnose and Treat
  Plantix/Images/crop-1.jpg
  Plantix/Images/crop-2.jpg
  Plantix/Images/crop-3.jpg
  Plantix/Images/crop-4.jpg
  Plantix/Images/google.png
  Plantix/Images/image1.jpg
  Plantix/Images/image2.png
  Plantix/Images/image3.png
  Plantix/Images/img-1.jpg
  Plantix/Images/img-2.jpg
  Plantix/Images/img-3.jpg
  Plantix/Images/img-4.jpg
  Plantix/Images/mobile.png
  Plantix/Images/mobile2.png
  Plantix/Images/mobile3.png
  Plantix/Images/plantix-logo.png
  Plantix/index.html
  Plantix/index.js
  Plantix/styles.css
Labels: GSSoC22, Level1

#685 Adobe photo shop clone
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/464526.gif
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/Adobe_Corporate_Horizontal_Red_HEX.svg
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/TC-4708-1.gif
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/adchoices-small.svg
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/ai_appicon_64_grayscale.svg
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/creative-cloud.svg
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/home_icon.svg
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/photoshop-localnav.css
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/photoshop-mobile.svg
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/ps_appicon.svg
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/ps_appicon_64_grayscale.svg
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/reader_appicon_64_grayscale.svg
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/social-icon-facebook.svg
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/social-icon-instagram.svg
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/social-icon-linkedin.svg
  Adobe Photoshop Clone/Official Adobe Photoshop _ Photo and design software_files/social-icon-twitter.svg
  Adobe Photoshop Clone/index.html
  Adobe Photoshop Clone/readme
Labels: GSSoC22, Level1

#693 Issue #690 resolved Alarm app
  Alarm App/app.js
  Alarm App/index.html
  Alarm App/preview.md
  Alarm App/style.css
Labels: GSSoC22, Level1

#697 CSS Finger scanning effect
  CSS Fingerprint Scanner Animation/fingerPrint_01.png
  CSS Fingerprint Scanner Animation/fingerPrint_02.png
  CSS Fingerprint Scanner Animation/index.html
  CSS Fingerprint Scanner Animation/style.css
Labels: GSSoC22, Level1

#702 Added glassmorphism portfolio website
  Glassmorphism Portfolio UI/Images/Background.png
  Glassmorphism Portfolio UI/Images/Logo.png
  Glassmorphism Portfolio UI/Images/User.png
  Glassmorphism Portfolio UI/Images/right arrow.png
  Glassmorphism Portfolio UI/Readme.md
  Glassmorphism Portfolio UI/index.html
  Glassmorphism Portfolio UI/script.js
  Glassmorphism Portfolio UI/style.css
Labels: GSSoC22, Level2

#700 Issue #699 resolved : Cute Cat Dressing Room
  CatGame/app.js
  CatGame/index.html
  CatGame/readme.md
  CatGame/style.css
Labels: GSSoC22

#709 Added sticky navigation
  Sticky Navigation/Readme.md
  Sticky Navigation/index.html
  Sticky Navigation/script.js
  Sticky Navigation/style.css
Labels: GSSoC22, Level1

#728 Added Email & Password Authentication Method
  Sign_Up_Login_Form/.gitignore
  Sign_Up_Login_Form/app.js
  Sign_Up_Login_Form/index.html
  Sign_Up_Login_Form/package-lock.json
Labels: GSSoC22, Level2

#735 Added Hoverboard project.
  HoverBoard/index.html
  HoverBoard/script.js
  HoverBoard/style.css
Labels: GSSoC22, Level1

#749 Stepbtstepform
  Step By Step Form/index.html
  Step By Step Form/readme.md
  Step By Step Form/script.js
  Step By Step Form/style.css
Labels: GSSoC22, Level1

#756 Added paypal payment gateway in ReactJs
  PayPal_PaymentGateway/README.md
  PayPal_PaymentGateway/package-lock.json
  PayPal_PaymentGateway/package.json
  PayPal_PaymentGateway/public/favicon.ico
  PayPal_PaymentGateway/public/index.html
  PayPal_PaymentGateway/public/logo192.png
  PayPal_PaymentGateway/public/logo512.png
  PayPal_PaymentGateway/public/manifest.json
  PayPal_PaymentGateway/public/paypal.gif
  PayPal_PaymentGateway/public/robots.txt
  PayPal_PaymentGateway/src/App.css
  PayPal_PaymentGateway/src/App.js
  PayPal_PaymentGateway/src/App.test.js
  PayPal_PaymentGateway/src/Components/PayPal/ReactPayPal.js
  PayPal_PaymentGateway/src/index.css
  PayPal_PaymentGateway/src/index.js
  PayPal_PaymentGateway/src/logo.svg
  PayPal_PaymentGateway/src/reportWebVitals.js
  PayPal_PaymentGateway/src/setupTests.js
  README.md
Labels: GSSoC22, Level2

#741 Added Mapty Project
  MaptyProject/.prettierrc
  MaptyProject/icon.png
  MaptyProject/index.html
  MaptyProject/logo.png
  MaptyProject/readme.txt
  MaptyProject/script.js
  MaptyProject/style.css
Labels: GSSoC22, Level2

#736 Added youtube clone
  Youtube Clone/Images/Explore.png
  Youtube Clone/Images/arrow.png
  Youtube Clone/Images/history.png
  Youtube Clone/Images/home.png
  Youtube Clone/Images/liked.png
  Youtube Clone/Images/logo.png
  Youtube Clone/Images/resume.png
  Youtube Clone/Images/video1.png
  Youtube Clone/Images/watch later.png
  Youtube Clone/Readme.md
  Youtube Clone/index.html
  Youtube Clone/script.js
  Youtube Clone/style.css
Labels: GSSoC22, Level1

#757 Added Covid Tracker in ReactJs
  Android-animation/Yhhvl.gif
  PayPal_PaymentGateway/package-lock.json
  PayPal_PaymentGateway/package.json
  PayPal_PaymentGateway/src/App.css
  PayPal_PaymentGateway/src/App.js
  PayPal_PaymentGateway/src/Components/PayPal/ReactPayPal.js
  PayPal_PaymentGateway/src/index.css
  PayPal_PaymentGateway/src/index.js
  covid-tracker/.gitignore
  covid-tracker/README.md
  covid-tracker/package-lock.json
  covid-tracker/package.json
  covid-tracker/public/covidtracker.png
  covid-tracker/public/favicon.ico
  covid-tracker/public/index.html
  covid-tracker/public/logo192.png
  covid-tracker/public/logo512.png
  covid-tracker/public/manifest.json
  covid-tracker/public/robots.txt
  covid-tracker/src/App.css
  covid-tracker/src/App.js
  covid-tracker/src/App.test.js
  covid-tracker/src/components/covidTracker/covid-tracker.js
  covid-tracker/src/components/covidTracker/details.js
  covid-tracker/src/index.css
  covid-tracker/src/index.js
  covid-tracker/src/logo.svg
  covid-tracker/src/redux/DetailsSlice.js
  covid-tracker/src/redux/countrySlice.js
  covid-tracker/src/redux/store.js
  covid-tracker/src/redux/todoSlice.js
  covid-tracker/src/reportWebVitals.js
  covid-tracker/src/setupTests.js
Labels: GSSoC22, Level1

#764 Pendulum ball
  Loading Effect Pendulum Ball/index.html
  Loading Effect Pendulum Ball/readme.md
  Loading Effect Pendulum Ball/style.css
Labels: GSSoC22, Level1

#763 Navmenu
  Navigation Menu Animated/index.html
  Navigation Menu Animated/preview3.gif
  Navigation Menu Animated/readme.md
  Navigation Menu Animated/style.css
Labels: GSSoC22, Level1

#765 Covid front
  Covid Frontend UI/index.html
  Covid Frontend UI/readme.md
  Covid Frontend UI/style.css
Labels: GSSoC22, Level1

#774 Qr code gen
  QR Code Generator/Readme.md
  QR Code Generator/assets/bootstrap/css/bootstrap.min.css
  QR Code Generator/assets/bootstrap/js/bootstrap.min.js
  QR Code Generator/assets/img/downloads-bg.jpg
  QR Code Generator/assets/img/intro-bg.jpg
  QR Code Generator/assets/js/grayscale.js
  QR Code Generator/index.html
  QR Code Generator/style.css
Labels: GSSoC22, Level1

#770 error page
  Error Page Animated/assets/preview.gif
  Error Page Animated/index.html
  Error Page Animated/style.css
Labels: GSSoC22, Level1

#771 Hover Menu
  Hover Menu/asset/1.png
  Hover Menu/asset/2.png
  Hover Menu/asset/3.png
  Hover Menu/index.html
  Hover Menu/style.css
Labels: GSSoC22, Level1

#773 Added Task Tracker in React JS
  README.md
  Task-Tracker/.gitignore
  Task-Tracker/README.md
  Task-Tracker/db.json
  Task-Tracker/package-lock.json
  Task-Tracker/package.json
  Task-Tracker/public/index.html
  Task-Tracker/public/robots.txt
  Task-Tracker/src/App.js
  Task-Tracker/src/components/AddTask.js
  Task-Tracker/src/components/Button.js
  Task-Tracker/src/components/Task.js
  Task-Tracker/src/components/Tasks.js
  Task-Tracker/src/components/header.js
  Task-Tracker/src/index.css
  Task-Tracker/src/index.js
  Task-Tracker/src/reportWebVitals.js
Labels: GSSoC22, Level2

#780 Issue #779 Responsive Task Management UI
  TaskManagement/app.js
  TaskManagement/index.html
  TaskManagement/readme.md
  TaskManagement/style.css
Labels: GSSoC22, Level1

#781 Quiz App using React and Typescript created
  README.md
  React-Quiz-App/.gitignore
  React-Quiz-App/package-lock.json
  React-Quiz-App/package.json
  React-Quiz-App/public/favicon.ico
  React-Quiz-App/public/index.html
  React-Quiz-App/public/manifest.json
  React-Quiz-App/public/robots.txt
  React-Quiz-App/src/API.ts
  React-Quiz-App/src/App.styles.ts
  React-Quiz-App/src/App.tsx
  React-Quiz-App/src/Components/Card.styles.ts
  React-Quiz-App/src/Components/Card.tsx
  React-Quiz-App/src/images/compbg2.jpg
  React-Quiz-App/src/index.tsx
  React-Quiz-App/src/react-app-env.d.ts
  React-Quiz-App/src/utils.ts
  React-Quiz-App/tsconfig.json
  Screenshots/react_quizz_app.png
Labels: GSSoC22, Level2

#776 Added appointment app in React JS
  appointment-app/.gitignore
  appointment-app/README.md
  appointment-app/appointment.jpg
  appointment-app/package-lock.json
  appointment-app/package.json
  appointment-app/public/favicon.ico
  appointment-app/public/index.html
  appointment-app/public/manifest.json
  appointment-app/src/App.css
  appointment-app/src/App.js
  appointment-app/src/App.test.js
  appointment-app/src/components/Form.js
  appointment-app/src/components/Table.js
  appointment-app/src/index.css
  appointment-app/src/index.js
  appointment-app/src/logo.svg
  appointment-app/src/registerServiceWorker.js
Labels: GSSoC22, Level2

#837 2 Side Nav Bar
  Side Navbars/Navbar1/index.html
  Side Navbars/Navbar1/preview.jpg
  Side Navbars/Navbar1/style.css
  Side Navbars/Navbar2/index.html
  Side Navbars/Navbar2/preview2.gif
  Side Navbars/Navbar2/script.js
  Side Navbars/Navbar2/style.css
Labels: GSSoC22, Level1

#791 Added Disney Plus Implementation
  Disney Plus Clone/app.js
  Disney Plus Clone/images/add.png
  Disney Plus Clone/images/disney.PNG
  Disney Plus Clone/images/geographic.PNG
  Disney Plus Clone/images/logo.png
  Disney Plus Clone/images/marvel.PNG
  Disney Plus Clone/images/nxt.png
  Disney Plus Clone/images/pixar.PNG
  Disney Plus Clone/images/play.png
  Disney Plus Clone/images/poster 1.png
  Disney Plus Clone/images/poster 10.png
  Disney Plus Clone/images/poster 11.png
  Disney Plus Clone/images/poster 12.png
  Disney Plus Clone/images/poster 2.png
  Disney Plus Clone/images/poster 3.png
  Disney Plus Clone/images/poster 4.png
  Disney Plus Clone/images/poster 5.png
  Disney Plus Clone/images/poster 6.png
  Disney Plus Clone/images/poster 7.png
  Disney Plus Clone/images/poster 8.png
  Disney Plus Clone/images/poster 9.png
  Disney Plus Clone/images/pre.png
  Disney Plus Clone/images/slider 1.PNG
  Disney Plus Clone/images/slider 2.PNG
  Disney Plus Clone/images/slider 3.PNG
  Disney Plus Clone/images/slider 4.PNG
  Disney Plus Clone/images/slider 5.PNG
  Disney Plus Clone/images/star-wars.PNG
  Disney Plus Clone/index.html
  Disney Plus Clone/script.js
  Disney Plus Clone/style.css
  Disney Plus Clone/videos/disney.mp4
  Disney Plus Clone/videos/geographic.mp4
  Disney Plus Clone/videos/marvel.mp4
  Disney Plus Clone/videos/pixar.mp4
  Disney Plus Clone/videos/star-war.mp4
Labels: GSSoC22, Level2

#840 #782 Meme generator using React.js
  Meme-Generator/README.md
  Meme-Generator/package.json
  Meme-Generator/preview.png
  Meme-Generator/public/favicon.ico
  Meme-Generator/public/images/troll-face.svg
  Meme-Generator/public/index.html
  Meme-Generator/public/manifest.json
  Meme-Generator/public/robots.txt
  Meme-Generator/src/App.css
  Meme-Generator/src/App.js
  Meme-Generator/src/Components/Header.js
  Meme-Generator/src/Components/Meme.js
  Meme-Generator/src/images/download-solid.svg
  Meme-Generator/src/images/troll-face.svg
  Meme-Generator/src/index.js
Labels: GSSoC22, Level3
