Repository Ayush7614/Bundli-Frontend, pull requests merged in 2022-04, with the labels that each got.

#594 Added Function Grapher Files
  Function_Grapher/assets/css/bootstrap.css
  Function_Grapher/assets/css/bootstrap.css.map
  Function_Grapher/assets/css/style.css
  Function_Grapher/index.html
  Function_Grapher/scripts/app.js
  Function_Grapher/scripts/bootstrap.bundle.js
  Function_Grapher/scripts/bootstrap.bundle.js.map
  Function_Grapher/scripts/function_plot.js
Labels: GSSoC22, Level1

#609 Added chatbot
  Chatbot/Hangout - Message.mp3
  Chatbot/iconfinder-send-4341325_120524.png
  Chatbot/index.html
  Chatbot/more_horiz_white_24dp.svg
  Chatbot/robot (1).png
  Chatbot/script.js
  Chatbot/style.css
Labels: accepted, GSSoC22, Level1

#598 Issue 588: Added Pig-Game
  .github/workflows/label.yml
  Pig-Game/dice-1.png
  Pig-Game/dice-2.png
  Pig-Game/dice-3.png
  Pig-Game/dice-4.png
  Pig-Game/dice-5.png
  Pig-Game/dice-6.png
  Pig-Game/index.html
  Pig-Game/pig-game-flowchart.png
  Pig-Game/script.js
  Pig-Game/style.css
Labels: accepted, Level1

#620 Creative Website Agency
  CreativeAgencyWebsite/contact.html
  CreativeAgencyWebsite/css/style.css
  CreativeAgencyWebsite/images/001.png
  CreativeAgencyWebsite/images/002.png
  CreativeAgencyWebsite/images/003.png
  CreativeAgencyWebsite/images/004.png
  CreativeAgencyWebsite/images/005.png
  CreativeAgencyWebsite/images/006.png
  CreativeAgencyWebsite/images/address.png
  CreativeAgencyWebsite/images/call.png
  CreativeAgencyWebsite/images/close.png
  CreativeAgencyWebsite/images/email.png
  CreativeAgencyWebsite/images/email2.png
  CreativeAgencyWebsite/images/facebook.png
  CreativeAgencyWebsite/images/home-img.jpg
  CreativeAgencyWebsite/images/img1.jpg
  CreativeAgencyWebsite/images/instagram.png
  CreativeAgencyWebsite/images/menu.png
  CreativeAgencyWebsite/images/portfolio-item1.jpg
  CreativeAgencyWebsite/images/portfolio-item10.jpg
  CreativeAgencyWebsite/images/portfolio-item11.jpg
  CreativeAgencyWebsite/images/portfolio-item12.jpg
  CreativeAgencyWebsite/images/portfolio-item13.jpg
  CreativeAgencyWebsite/images/portfolio-item14.jpg
  CreativeAgencyWebsite/images/portfolio-item15.jpg
  CreativeAgencyWebsite/images/portfolio-item16.jpg
  CreativeAgencyWebsite/images/portfolio-item2.jpg
  CreativeAgencyWebsite/images/portfolio-item3.jpg
  CreativeAgencyWebsite/images/portfolio-item4.jpg
  CreativeAgencyWebsite/images/portfolio-item5.jpg
  CreativeAgencyWebsite/images/portfolio-item6.jpg
  CreativeAgencyWebsite/images/portfolio-item7.jpg
  CreativeAgencyWebsite/images/portfolio-item8.jpg
  CreativeAgencyWebsite/images/portfolio-item9.jpg
  CreativeAgencyWebsite/images/screenshot.png
  CreativeAgencyWebsite/images/twitter.png
  CreativeAgencyWebsite/index.html
  CreativeAgencyWebsite/js/script.js
  CreativeAgencyWebsite/services.html
  CreativeAgencyWebsite/work.html
Labels: GSSoC22, Level1

#618 added a expadable card
  card/index.html
  card/style.css
Labels: GSSoC22, Level1

#616 Adding the memory game
  Emoji Memory Game/index.html
  Emoji Memory Game/index.js
  Emoji Memory Game/styles.css
Labels: GSSoC22, Level1

#629 Burger Eye
  Burger Eye/README.md
  Burger Eye/burger.png
  Burger Eye/favicon.png
  Burger Eye/index.html
  Burger Eye/index.js
  Burger Eye/style.css
Labels: GSSoC22, Level1

#625 Final Commit of Weather Application
  Weather App/app.js
  Weather App/index.html
  Weather App/styles.css
Labels: GSSoC22, Level1

#647 Portfolio website
  Portfolio website/README.md
  Portfolio website/images/1.webp
  Portfolio website/images/2.jpg
  Portfolio website/images/3.jpg
  Portfolio website/images/4.jpeg
  Portfolio website/images/5.jpg
  Portfolio website/images/6.jpg
  Portfolio website/images/7.jpg
  Portfolio website/images/bg.jpg
  Portfolio website/images/bg2.jpg
  Portfolio website/images/bg3.webp
  Portfolio website/index.html
  Portfolio website/script.js
  Portfolio website/style.css
Labels: GSSoC22, Level1

#646 Added the responsive landing page to Bundli-Frontend
  Responsive-Landing-Page/index.html
  Responsive-Landing-Page/logo.png
  Responsive-Landing-Page/person.png
  Responsive-Landing-Page/script.js
  Responsive-Landing-Page/shape.png
  Responsive-Landing-Page/style.css
Labels: GSSoC22, Level1

#641 Added google keep clone
  Google_Keep_Notes_Clone/.gitignore
  Google_Keep_Notes_Clone/README.md
  Google_Keep_Notes_Clone/package-lock.json
  Google_Keep_Notes_Clone/package.json
  Google_Keep_Notes_Clone/public/index.html
  Google_Keep_Notes_Clone/public/manifest.json
  Google_Keep_Notes_Clone/public/robots.txt
  Google_Keep_Notes_Clone/src/App.js
  Google_Keep_Notes_Clone/src/CreateNote.js
  Google_Keep_Notes_Clone/src/Footer.js
  Google_Keep_Notes_Clone/src/Header.js
  Google_Keep_Notes_Clone/src/Note.js
  Google_Keep_Notes_Clone/src/index.js
  Google_Keep_Notes_Clone/src/style.css
Labels: GSSoC22, Level2

#642 Long Drive
  Long Drive/README.md
  Long Drive/index.html
  Long Drive/style.css
Labels: GSSoC22, Level1

#637 Final website of Letter_Doc_Request_Generator
  Leave_Doc_Req_Generation/doc.ico
  Leave_Doc_Req_Generation/document.html
  Leave_Doc_Req_Generation/formstyle.css
  Leave_Doc_Req_Generation/image.jpg
  Leave_Doc_Req_Generation/index.html
  Leave_Doc_Req_Generation/letter.html
  Leave_Doc_Req_Generation/letter.ico
  Leave_Doc_Req_Generation/school.ico
  Leave_Doc_Req_Generation/script.js
  Leave_Doc_Req_Generation/style.css
Labels: GSSoC22, Level2

#653 Added Airbnb UI Clone
  Airbnb Clone UI/.gitignore
  Airbnb Clone UI/package-lock.json
  Airbnb Clone UI/package.json
  Airbnb Clone UI/public/favicon.ico
  Airbnb Clone UI/public/index.html
  Airbnb Clone UI/src/App.js
  Airbnb Clone UI/src/Components/Footer/Footer.js
  Airbnb Clone UI/src/Components/Navbar/Logic.js
  Airbnb Clone UI/src/Components/Navbar/Navbar.js
  Airbnb Clone UI/src/Pages/Home.js
  Airbnb Clone UI/src/Utils/Heading.js
  Airbnb Clone UI/src/Utils/Media.js
  Airbnb Clone UI/src/Utils/Theme.js
  Airbnb Clone UI/src/Utils/images/house.jpg
  Airbnb Clone UI/src/index.css
  Airbnb Clone UI/src/index.js
  Airbnb Clone UI/src/sections/Discover.js
  Airbnb Clone UI/src/sections/Experiences.js
  Airbnb Clone UI/src/sections/FlexibleDes.js
Labels: GSSoC22, Level2

#661 Added Dog website template files
  NekoWip/comingSoon.html
  NekoWip/css-code/cat.jpg
  NekoWip/css-code/dog.jpg
  NekoWip/css-code/favicon.ico
  NekoWip/css-code/forest.css
  NekoWip/css-code/forest.jpg
  NekoWip/css-code/styles.css
  NekoWip/index.html
Labels: GSSoC22, Level1

#677 Added Manage Landing Page
  Manage Landing Page/README.md
  Manage Landing Page/app.js
  Manage Landing Page/css/style.css
  Manage Landing Page/images/avatar-ali.png
  Manage Landing Page/images/avatar-anisha.png
  Manage Landing Page/images/avatar-richard.png
  Manage Landing Page/images/avatar-shanai.png
  Manage Landing Page/images/bg-simplify-section-desktop.svg
  Manage Landing Page/images/bg-simplify-section-mobile.svg
  Manage Landing Page/images/bg-tablet-pattern.svg
  Manage Landing Page/images/favicon-32x32.png
  Manage Landing Page/images/icon-close.svg
  Manage Landing Page/images/icon-facebook.svg
  Manage Landing Page/images/icon-hamburger.svg
  Manage Landing Page/images/icon-instagram.svg
  Manage Landing Page/images/icon-pinterest.svg
  Manage Landing Page/images/icon-twitter.svg
  Manage Landing Page/images/icon-youtube.svg
  Manage Landing Page/images/illustration-intro.svg
  Manage Landing Page/images/logo footer.svg
  Manage Landing Page/images/logo.svg
  Manage Landing Page/images/screenshot (2).jpg
  Manage Landing Page/index.html
  Manage Landing Page/style-guide.md
Labels: GSSoC22, Level1

#676 Added Atlas
  Atlas Countries/README.md
  Atlas Countries/package-lock.json
  Atlas Countries/package.json
  Atlas Countries/postcss.config.js
  Atlas Countries/public/favicon.ico
  Atlas Countries/public/index.html
  Atlas Countries/public/logo192.png
  Atlas Countries/public/logo512.png
  Atlas Countries/public/manifest.json
  Atlas Countries/public/robots.txt
  Atlas Countries/src/App.js
  Atlas Countries/src/api/api.js
  Atlas Countries/src/api/api_countries.js
  Atlas Countries/src/components/Dropdown/Dropdown.jsx
  Atlas Countries/src/components/Search/Search.jsx
  Atlas Countries/src/components/Search/useDebounce.js
  Atlas Countries/src/index.css
  Atlas Countries/src/index.js
  Atlas Countries/src/pages/Country_Details.jsx
  Atlas Countries/src/pages/Home.jsx
  Atlas Countries/src/useDarkMode.js
  Atlas Countries/tailwind.config.js
Labels: GSSoC22, Level1

#673 Particle Animation for Image
  Image Particle Animation/index.html
  Image Particle Animation/readme.md
  Image Particle Animation/script.js
  Image Particle Animation/style.css
Labels: GSSoC22, Level1
